name: Kustomize Set Image Tag
description: Patches a new image tag into a kubernetes project via 'kustomize edit image'

inputs:
  github-token:
    description: Github token with permissions to push commits to the given manifests-repository
    required: true

  manifests-repository:
    description: Github repository containing deployment manifests to kustomize
    required: true

  manifests-ref:
    description: Github reference to a commit or branch where kustomize will push changes.  If this ref is a branch, it must exist as it will not be created.
    required: true
    
  manifests-path:
    description: Relative path to the directory containing the desired kustomization file to modify within the manifests-repository
    required: true

  image:
    description: The fully-qualified image name to pin via kustomize
    required: true
    
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.manifests-repository }}
        ref: ${{ inputs.manifests-ref }}
        token: ${{ inputs.github-token }}

    - name: Setup Kustomize
      id: setup-kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Kustomize Image Tag
      id: kustomize-image-tag
      shell: bash
      run: |
        cd ${{ inputs.manifests-path }}
        kustomize edit set image ${{ inputs.image }}
    
    - name: Set Git user and email
      id: set-git-identity
      shell: bash
      run: |
        git config --global user.email "build@vela.care"
        git config --global user.name "kustomize-github-workflow"

    # Decompose the image metadata from the image name input.
    # There is no validation on these parameters; output values may be null!
    - name: Get image metadata
      id: image-metadata
      shell: bash
      run: |
        IMAGE_REGISTRY=$(echo ${{ inputs.image }}   | sed -E 's/^([0-9]{12}\.dkr\.ecr.([^.]+)\.amazonaws\.com)\/([^:]+):(.*)$/\1/')
        IMAGE_REGION=$(echo ${{ inputs.image }}     | sed -E 's/^([0-9]{12}\.dkr\.ecr.([^.]+)\.amazonaws\.com)\/([^:]+):(.*)$/\2/')
        IMAGE_REPOSITORY=$(echo ${{ inputs.image }} | sed -E 's/^([0-9]{12}\.dkr\.ecr.([^.]+)\.amazonaws\.com)\/([^:]+):(.*)$/\3/')
        IMAGE_TAG=$(echo ${{ inputs.image }}        | sed -E 's/^([0-9]{12}\.dkr\.ecr.([^.]+)\.amazonaws\.com)\/([^:]+):(.*)$/\4/')
        echo "::set-output name=image-registry::$IMAGE_REGISTRY"
        echo "::set-output name=image-region::$IMAGE_REGION"
        echo "::set-output name=image-repository::$IMAGE_REPOSITORY"
        echo "::set-output name=image-tag::$IMAGE_TAG"

    - name: Push to SCM repository
      id: push-to-scm
      shell: bash
      run: |
        git checkout ${{ inputs.manifests-ref }}
        echo '--------------------------'
        git commit -am "automation: kustomize set image for ${{ steps.image-metadata.outputs.image-repository }}" \
          -m "${{ steps.image-metadata.outputs.image-repository }} project set to image ${{ steps.image-metadata.outputs.image-tag }}"
        echo '--------------------------'
        git push
